### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by Ayushlion8** [iiitl/Redemption-2024#1]
Create histograms or density plots to visualize the distribution of numerical features.

Dataset :  'insurance.csv'

**Comment by Ajayantil7** [comment]
@Ayushlion8 I can solve this issue, please assign it to me.

**Comment by AMANVISHWAKARMA27** [comment]
I would like to work on the issue, kindly assign it to me.

**Comment by Ayushlion8** [comment]
@Invincible1602, issue assigned to you.

**Comment by Ayushlion8** [comment]
don't ask for assignment just solve the issues as fast as possible.😊

**Comment by AMANVISHWAKARMA27** [comment]
@Ayushlion8  one doubt, do we have to represent all the values in one histogram or separately for each.

**Comment by Ayushlion8** [comment]
@AMANVISHWAKARMA27 bhai sabka seperately dikhaana tha but ab toh close ho gyi yeah issue.
Try in another one bro😊
