### ISSUE TITLE
Perform Exploratory Data Analysis

### ISSUE THREAD

**Issue by mitalijambhulkar67** [iiitl/Redemption-2024#18]
Task : Perform Exploratory Data Analysis on the given dataset to find :

1. Season which had most number of matches.
2. Which team is the winner in most of the matches.
3. Number of matches in each venue.
4. Number of matches played by each team.
5. Number of wins per team.
6. Top players of the match.

Dataset : matches.csv
Submission Format : Submit a Colab file with all the functions mentioned in the task.

**Comment by YuwanshB005** [comment]
@mitalijambhulkar67 I can solve this issue , please assign it to me

**Comment by Ajayantil7** [comment]
@mitalijambhulkar67 I can solve this issue, please assign it to me.

**Comment by Invincible1602** [comment]
@mitalijambhulkar67 , I want to solve this issue, please assign it to me
