### ISSUE TITLE
Outlier Detection Techniques

### ISSUE THREAD

**Issue by maskboyAvi** [iiitl/Redemption-2024#8]
Dataset to be used - https://www.kaggle.com/datasets/ruchi798/ionosphere-radar-returns/data

Task -:
 Detect outliers in the dataset using -
 1. Box Plot - Draw boxplot of each feature in the dataset to see outliers . 
 2. IQR Method - Apply this method and show outliers of each feature in a scatterplot graphs.
 3. Z Score Method - Apply this and show outliers of each feature in a scatterplot graph.
 
Note -: Each graph should be clearly visible.

Submission Format -: Colab File with all the code and output.

**Comment by YuwanshB005** [comment]
@maskboyAvi I can solve this issue, please assign it to me

**Comment by Invincible1602** [comment]
@maskboyAvi I want to solve this issue please assign me

**Comment by Ajayantil7** [comment]
@maskboyAvi I can solve this issue, please assign it to me.
